# Generated by Django 3.1.7 on 2021-03-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210318_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floraoccurrence',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='floraoccurrence',
            name='lon',
            field=models.FloatField(blank=True),
        ),
    ]
