# Generated by Django 3.1.7 on 2021-05-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210506_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fenomenos',
            new_name='Fenomeno',
        ),
    ]
