# Generated by Django 3.1.7 on 2021-03-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floraoccurrence',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floraoccurrence',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
