# Generated by Django 3.1.7 on 2021-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210318_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floraoccurrence',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floraoccurrence',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
