# Generated by Django 3.1.7 on 2021-05-06 01:17

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210425_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fenomenos',
            old_name='name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='fenomenos',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fenomenos',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='fenomenos',
            name='geom',
            field=djgeojson.fields.PointField(blank=True),
        ),
    ]
